#!/bin/sh

DO_ABF_BUILD=true
if [ "$1" = "-n" ]; then
	DO_ABF_BUILD=false
	shift
fi

if echo $1 |grep -q '\.buildlist'; then
	cat $1 |while read r; do
		for pkg in $r; do
			p=`echo $pkg |sed -e 's,openmandriva/,,'`
			$0 -n $p
		done
	done
	$DO_ABF_BUILD && abf chain_build --testing -b rolling -a aarch64 -a armv7hnl -a znver1 -a x86_64 -a i686 --auto-publish-status testing --no-cached-chroot --update-type enhancement -i $1
	exit 0
fi

D="$(mktemp -d /tmp/c2rXXXXXX)"

error() {
	echo "$@" >/dev/stderr
	cd /
	rm -rf "$D"
	exit 1
}

if [ -z "$D" ]; then
	echo "Couldn't create temporary directory"
	exit 1
fi
if [ -z "$1" ]; then
	echo "Usage: $0 package name"
	exit 1
fi

cd "$D"
if git clone -b rolling git@github.com:OpenMandrivaAssociation/$1; then
	cd $1
	if ! git merge origin/master; then
		error "Couldn't automatically merge branches. Please try manually."
	fi
elif git clone git@github.com:OpenMandrivaAssociation/$1; then
	cd $1
	git checkout -b rolling origin/master
else
	error "Couldn't find repository for $1 - bad package name?"
fi
git push origin rolling
$DO_ABF_BUILD && abf chain_build -b rolling -a aarch64 -a armv7hnl -a znver1 -a x86_64 -a i686 --auto-publish-status testing --no-cached-chroot --update-type enhancement openmandriva/$1
