#!/bin/sh
D="$(mktemp -d /tmp/c2rXXXXXX)"
rock_b=6.0
error() {
	echo "$@" >/dev/stderr
	cd /
	rm -rf "$D"
	exit 1
}

if [ -z "$D" ]; then
	echo "Couldn't create temporary directory"
	exit 1
fi
if [ "$1" = "-f" -o "$1" = "--force" ]; then
	FORCE=true
	shift
fi
if [ -z "$1" ]; then
	echo "Usage: $0 package name"
	exit 1
fi
cd "$D"
if [ "$FORCE" = "true" ]; then
	if git clone git@github.com:OpenMandrivaAssociation/$1; then
		cd $1
		if ! git checkout -b $rock_b origin/rolling; then
			error "No rolling branch - maybe you need to use cooker2rolling first"
		fi
		git push --force origin $rock_b
	else
		error "Couldn't find repository for $1 - bad package name?"
	fi
else
	if git clone -b $rock_b git@github.com:OpenMandrivaAssociation/$1; then
		cd $1
		if ! git merge origin/rolling; then
			error "Couldn't automatically merge branches. Please try manually."
		fi
	elif git clone git@github.com:OpenMandrivaAssociation/$1; then
		cd $1
		git checkout -b $rock_b origin/rolling
	else
		error "Couldn't find repository for $1 - bad package name?"
	fi
	git push origin $rock_b
fi
abf chain_build -b $rock_b -a aarch64 -a znver1 -a x86_64 --auto-publish-status testing --no-cached-chroot --update-type enhancement openmandriva/$1
