#!/bin/sh
# Usage: update-kapps version [startfrom]
# 	version: KDE Applications version to update to
#	startfrom: Package to start from (e.g. to continue where
#		a previous build left off because of a patch rebase
#		or file list issue)
#
# (C) 2015 Bernhard Rosenkränzer <bero@lindev.ch>
# Released under the terms of the GPLv3

echo "$0 is deprecated -- use:"
echo "update kapps $@"
exec $(dirname $0)/update kapps "$@"
