#!/bin/sh
# Usage: update-kf version [startfrom]
# 	version: KDE Frameworks version to update to
#	startfrom: Package to start from (e.g. to continue where
#		a previous build left off because of a patch rebase
#		or file list issue)
#
# (C) 2015 Bernhard Rosenkränzer <bero@lindev.ch>
# Released under the terms of the GPLv3

error() {
	echo "$1 failed to build -- please see above and fix."
	exit 1
}

if [ "$#" -lt 1 ]; then
	echo "Specify the version to update to"
	exit 1
fi

VERSION="$1"
#PACKAGES="extra-cmake-modules5 attica5 networkmanager-qt kitemmodels kitemviews karchive kcodecs kconfig kcoreaddons kdbusaddons kguiaddons kidletime kimageformats kplotting kwidgetsaddons kwindowsystem kcrash solid sonnet threadweaver ki18n kglobalaccel kjs kdnssd5 kauth kcompletion kdoctools kjobwidgets kunitconversion kpty kservice kjsembed kconfigwidgets kdesu kemoticons kiconthemes kapidox knotifications ktextwidgets kxmlgui kwallet5 kbookmarks kcmutils kio kparts kinit kdeclarative knewstuff knotifyconfig kactivities frameworkintegration kdesignerplugin khtml ktexteditor kdewebkit kross kpackage plasma-framework krunner kmediaplayer kded kdelibs4support"
PACKAGES="$(cat $(dirname $0)/kf.buildlist |sed -e 's,openmandriva/,,g')"
REALVERSION="${VERSION}"

if [ "$#" -ge 2 ]; then
	P=""
	RELEVANT=0
	for i in $PACKAGES; do
		[ "$i" = "$2" ] && RELEVANT=1
		[ "$RELEVANT" = "1" ] && P="$P $i"
	done
	PACKAGES="$P"
fi

for i in $PACKAGES; do
	# Versioning for extra-cmake-modules seems to have adapted to
	# regular versioning in 5.9...
	#if [ "$i" = "extra-cmake-modules5" ]; then
	#	VERSION="$(echo ${VERSION} |sed -e 's,^5,1,')"
	#fi
	rm -rf ${i}
	git clone git@abf.io:/openmandriva/${i}.git || error $i
	 pushd ${i}
	OLDVERSION="$(grep -i '^Version[[:space:]]*:' *.spec |cut -d: -f2 |xargs echo)"
	OLDEXP="$(echo ${OLDVERSION} |sed -e 's,\.,\\.,g')"
	sed -i -e "/${OLDEXP}\.tar/d" .abf.yml
	sed -i -e "s,/frameworks/%{version},/frameworks/%(echo %{version} |cut -d. -f1-2),g" *.spec
	sed -i -e "s,^\(Version.*:.*\)${OLDEXP},\1${VERSION}," *.spec
	sed -i -e "s,^\(Release.*:\s*\)[0-9]*,\11," *.spec
	if [ "$i" = "attica5" -o "$i" = "kwallet5" -o "$i" = "baloo5" -o "$i" = "kfilemetadata5" ]; the
            wget http://download.kde.org/stable/frameworks/$(echo $REALVERSION |cut -d. -f1-2)/${i%?}-$REALVERSION.tar.xz || error $i
            sha1sum ${i%?}-${REALVERSION}.tar.xz | awk '{print "  "$2": "  $1}' >> .abf.yml || error $i
        elif [ "$i" = "kdelibs4support" -o "$i" = "khtml" -o "$i" = "kjs" -o "$i" = "kjsembed" -o "$i" = "kmediaplayer" -o "$i" = "kross" -o "$i" = "krunner" ]; then
            wget http://download.kde.org/stable/frameworks/$(echo $REALVERSION |cut -d. -f1-2)/portingAids/${i}-$REALVERSION.tar.xz || error $i
	    sha1sum ${i}-${REALVERSION}.tar.xz | awk '{print "  "$2": "  $1}' >> .abf.yml || error $i
        else
	    wget http://download.kde.org/stable/frameworks/$(echo $REALVERSION |cut -d. -f1-2)/${i}-$REALVERSION.tar.xz || error $i
	    sha1sum ${i}-${REALVERSION}.tar.xz | awk '{print "  "$2": "  $1}' >> .abf.yml || error $i
	fi

	abf store *-$REALVERSION.tar* || error $i
	rm -rf $i*-$REALVERSION.tar.xz
	git commit -am "Update to ${VERSION}" || error $i
	git push origin master
	git remote set-url --add --push origin git@github.com:OpenMandrivaAssociation/${i}.git
	git push
	popd
	VERSION="${REALVERSION}"
done

#abf chain_build -b master --update-type enhancement -i $(dirname $0)/kf.buildlist
