#!/bin/sh
# Usage: update-pd version [startfrom]
# 	version: Plasma Desktop version to update to
#	startfrom: Package to start from (e.g. to continue where
#		a previous build left off because of a patch rebase
#		or file list issue)
#
# (C) 2015 Bernhard Rosenkränzer <bero@lindev.ch>
# Released under the terms of the GPLv3

error() {
	echo "$1 failed to build -- please see above and fix."
	exit 1
}

if [ "$#" -lt 1 ]; then
	echo "Specify the version to update to"
	exit 1
fi

VERSION="$1"
PACKAGES="$(cat $(dirname $0)/pd.buildlist |sed -e 's,openmandriva/,,g')"
REALVERSION="${VERSION}"

if [ "$#" -ge 2 ]; then
	P=""
	RELEVANT=0
	for i in $PACKAGES; do
		[ "$i" = "$2" ] && RELEVANT=1
		[ "$RELEVANT" = "1" ] && P="$P $i"
	done
	PACKAGES="$P"
fi

for i in $PACKAGES; do
	rm -rf ${i}
	git clone git@abf.io:/openmandriva/${i}.git || error $i
#	 pushd ${i}
#        if `ls *.spec >/dev/null`;  then
#            for branch in `git branch -a | grep remotes | grep -v HEAD | grep -v master`; do
#                git branch --track ${branch##*/} $branch
#            done
#            git fetch --all
#            git pull --all
#            git remote set-url --push origin git@github.com:OpenMandrivaAssociation/${i}.git
#            git push --mirror git@github.com:OpenMandrivaAssociation/${i}.git
#        else
#            echo "No spec file found"
#        fi
#    popd

	cd ${i}
	OLDVERSION="$(grep -i '^Version[[:space:]]*:' *.spec |cut -d: -f2 |xargs echo)"
	OLDEXP="$(echo ${OLDVERSION} |sed -e 's,\.,\\.,g')"
	sed -i -e "/${OLDEXP}\.tar/d" .abf.yml
	sed -i -e "s,/frameworks/%{version},/frameworks/%(echo %{version} |cut -d. -f1-2),g" *.spec
	PKGVERSION=${VERSION}
	sed -i -e "s,^\(Version.*:.*\)${OLDEXP},\1${PKGVERSION}," *.spec
	sed -i -e "s,^\(Release.*:\s*\)[0-9]*,\11," *.spec
	if [ "$i" = "libkscreen5" -o "$i" = "bluedevil5" -o "$i" = "kde-gtk-config5" -o "$i" = "kscreen5" -o "$i" = "kdeplasma-addons5" ]; then
	    wget http://download.kde.org/stable/plasma/$VERSION/${i%?}-$PKGVERSION.tar.xz || error $i
	    sha1sum ${i%?}-${PKGVERSION}.tar.xz | awk '{print "  "$2": "  $1}' >> .abf.yml
	else
		wget http://download.kde.org/stable/plasma/$VERSION/${i}-$PKGVERSION.tar.xz || error $i
		sha1sum ${i}-${PKGVERSION}.tar.xz | awk '{print "  "$2": "  $1}' >> .abf.yml
	fi

        abf store *-$PKGVERSION.tar.* || error $i
        rm -rf *-$PKGVERSION.tar.xz
	git commit -am "Update to $PKGVERSION" || error $i
	git push origin master
	cd ..
	VERSION="$REALVERSION"
done

#abf chain_build -b master --update-type enhancement -i $(dirname $0)/pd.buildlist
