#!/bin/sh
# Usage: update-kf version [startfrom]
# 	version: KDE Frameworks version to update to
#	startfrom: Package to start from (e.g. to continue where
#		a previous build left off because of a patch rebase
#		or file list issue)
#
# (C) 2015 Bernhard Rosenkränzer <bero@lindev.ch>
# Released under the terms of the GPLv3

error() {
	echo "$1 failed to build -- please see above and fix."
	exit 1
}

if [ "$#" -lt 1 ]; then
	echo "Specify the version to update to"
	exit 1
fi

VERSION="$1"
PACKAGES="extra-cmake-modules5 attica5 networkmanager-qt kitemmodels kitemviews karchive kcodecs kconfig kcoreaddons kdbusaddons kglobalaccel kguiaddons kidletime kimageformats kplotting kwidgetsaddons kwindowsystem solid sonnet threadweaver ki18n kjs kdnssd5 kauth kcompletion kcrash kdoctools kjobwidgets kunitconversion kpty kservice kjsembed kconfigwidgets kdesu kemoticons kiconthemes kapidox knotifications ktextwidgets kxmlgui kwallet5 kbookmarks kcmutils kio kparts kinit kdeclarative knewstuff knotifyconfig kactivities frameworkintegration kdesignerplugin khtml ktexteditor kdewebkit kross kpackage plasma-framework krunner kmediaplayer kded kdelibs4support"
REALVERSION="${VERSION}"

if [ "$#" -ge 2 ]; then
	P=""
	RELEVANT=0
	for i in $PACKAGES; do
		[ "$i" = "$2" ] && RELEVANT=1
		[ "$RELEVANT" = "1" ] && P="$P $i"
	done
	PACKAGES="$P"
fi

for i in $PACKAGES; do
	if [ "$i" = "extra-cmake-modules5" ]; then
		VERSION="$(echo ${VERSION} |sed -e 's,^5,1,')"
	fi
	rm -rf ${i}
	git clone git@abf.io:/openmandriva/${i}.git || error $i
	cd ${i}
	OLDVERSION="$(grep -i '^Version[[:space:]]*:' *.spec |cut -d: -f2 |xargs echo)"
	OLDEXP="$(echo ${OLDVERSION} |sed -e 's,\.,\\.,g')"
	sed -i -e "/${OLDEXP}\.tar/d" .abf.yml
	sed -i -e "s,/frameworks/%{version},/frameworks/%(echo %{version} |cut -d. -f1-2),g" *.spec
	sed -i -e "s,^\(Version.*:.*\)${OLDEXP},\1${VERSION}," *.spec
	sed -i -e "s,^\(Release.*:\s*\)[0-9]*,\11," *.spec
	sudo urpmi --auto --buildrequires *.spec
	abb build || error $i
	[ -d RPMS/`uname -m` ] || [ -d RPMS/noarch ] || error $i
	abb store *-${VERSION}.tar* || error $i
	git commit -am "Update to ${VERSION}" || error $i
	git push origin master
	sudo urpmi --auto RPMS/*/*.rpm
	cd ..
	VERSION="${REALVERSION}"
done
