#!/bin/sh
# Usage: update-papyros $(date +%Y%m%d)
# (C) 2015 Alexander Khryukinr <alexander@mezon.ru>
# Released under the terms of the GPLv3
error() {
	echo "$1 failed to build -- please see above and fix."
	exit 1
}
git_update() {
	echo "cloning $i repo"
	git clone https://github.com/papyros/$i.git
	pushd $i
	git archive --format=tar --prefix $i-0.0.0-$(date +%Y%m%d)/ HEAD | xz -vf > ../$i-0.0.0-$(date +%Y%m%d).tar.xz
	popd
}

if [ "$#" -lt 1 ]; then
	echo "Specify the version to update to"
	exit 1
fi

VERSION="$1"

PACKAGES="$(cat $(dirname $0)/papyros.buildlist |sed -e 's,openmandriva/,,g')"
REALVERSION="${VERSION}"

if [ "$#" -ge 2 ]; then
	P=""
	RELEVANT=0
	for i in $PACKAGES; do
		[ "$i" = "$2" ] && RELEVANT=1
		[ "$RELEVANT" = "1" ] && P="$P $i"
	done
	PACKAGES="$P"
fi

for i in $PACKAGES; do
	rm -rf ${i}
	git clone git@abf.io:/openmandriva/${i}.git || error $i
	cd ${i}
	git_update
	OLDVERSION="$(grep -i 'snap[[:space:]][0-9]*' *.spec | cut -d$'\t' -f 2 |xargs echo)"
	OLDEXP="$(echo ${OLDVERSION} |sed -e 's,\.,\\.,g')"
	sed -i -e "/${OLDEXP}\.tar/d" .abf.yml
	sed -i -e "s,${OLDEXP},${VERSION}," *.spec
	sed -i -e "s,^\(Release.*:\s*\)[0-9]*,\11," *.spec
	sudo urpmi --auto --buildrequires *.spec
	abb build || error $i
	[ -d RPMS/`uname -m` ] || [ -d RPMS/noarch ] || error $i
	abb store *-${VERSION}.tar* || error $i
	git commit -am "Update to ${VERSION}" || error $i
	git push origin master
	sudo urpmi --auto RPMS/*/*.rpm
	cd ..
	VERSION="${REALVERSION}"
done

abf chain_build -b master --update-type enhancement -i $(dirname $0)/papyros.buildlist
