#!/bin/sh
# Usage: update-qt version [startfrom]
# 	version: Qt version to update to
#	startfrom: Package to start from (e.g. to continue where
#		a previous build left off because of a patch rebase
#		or file list issue)
#
# (C) 2015 Bernhard Rosenkränzer <bero@lindev.ch>
# Released under the terms of the GPLv3

error() {
	echo "$1 failed to build -- please see above and fix."
	exit 1
}

if [ "$#" -lt 1 ]; then
	echo "Specify the version to update to"
	exit 1
fi

VERSION="$1"
PACKAGES="$(cat $(dirname $0)/qt.buildlist |sed -e 's,openmandriva/,,g')"
REALVERSION="${VERSION}"

if [ "$#" -ge 2 ]; then
	P=""
	RELEVANT=0
	for i in $PACKAGES; do
		[ "$i" = "$2" ] && RELEVANT=1
		[ "$RELEVANT" = "1" ] && P="$P $i"
	done
	PACKAGES="$P"
fi

for i in $PACKAGES; do
	rm -rf ${i}
	git clone git@abf.io:/openmandriva/${i}.git || error $i
	cd ${i}
	OLDVERSION="$(grep -i '^Version[[:space:]]*:' *.spec |cut -d: -f2 |xargs echo)"
	OLDEXP="$(echo ${OLDVERSION} |sed -e 's,\.,\\.,g')"
	sed -i -e "/${OLDEXP}\.tar/d" .abf.yml
	PKGVERSION=${VERSION}
	sed -i -e "s,^\(Version.*:.*\)${OLDEXP},\1${PKGVERSION}," *.spec
	sed -i -e "s,^\(Release.*:\s*\)[0-9]*,\11," *.spec
	sed -i -e "s,define beta rc,define beta %nil," *.spec
#	sed -i -e "s/^Release.*:.*%{beta}.*/Release:\t0.%{beta}.1/" *.spec
#	wget http://download.qt.io/development_releases/qt/5.5/5.5.0-beta/submodules/$(echo ${i}-opensource-src-5.5.0-beta.tar.xz | sed -i -e 's/qt5-//')
	name=${i##qt5-}-opensource-src-$PKGVERSION.tar.xz
	#wget http://download.qt.io/development_releases/qt/5.5/5.5.0-rc/submodules/$name || error $i
	wget http://download.qt.io/official_releases/qt/5.5/$PKGVERSION/submodules/$name || error $i
	sed -i -e "/qt.*alpha.tar.xz.*/d" .abf.yml
	sed -i -e "/qt.*beta.tar.xz.*/d" .abf.yml
	sed -i -e "/qt.*rc.tar.xz.*/d" .abf.yml
	sha1sum qt*-opensource-src-$PKGVERSION.tar.xz | awk '{print "  "$2": "  $1}' >> .abf.yml


#	sudo urpmi --auto --buildrequires *.spec
#	abb build || error $i
#	[ -d RPMS/`uname -m` ] || [ -d RPMS/noarch ] || error $i
	abf store qt*-opensource-src-$PKGVERSION.tar.xz || error $i
	rm -rf qt*-opensource-src-$PKGVERSION.tar.xz
	git commit -am "Update to $PKGVERSION final" || error $i
	git push origin master
#	sudo urpmi --auto RPMS/*/*.rpm
	cd ..
	VERSION="${REALVERSION}"
done

#abf chain_build -b master --update-type enhancement -i $(dirname $0)/qt.buildlist
